### ISSUE TITLE
Rename MiniGame Modules

### ISSUE THREAD

**Issue by sandersonsans** [SergioAnderson/lms-scripts#1]
Rename files in style to following format:

Example:

- Mini Game
- -Gmi10100 You Are The Shield   On Call Mini Game
- -Mod109 Mg01 Browsing Safely   Secure Shopping Mini Game Mini Game
- Gamified
- -Gmi00101 Secure The Office   - Room 1 Workstations
- Applied Interactive
- -Applied Interactive Modules - Browsing Safely
- Hostled
- -Mod101-flavorHostLed - You Are the Shield
- Illustrative Design
- -ModIDN10100-flavorTraditional - You Are the Shield
- Live Action
- -Mod101-flavorLiveAction - You Are the Shield
- Secure The Family
- -ModDCY12900-flavorTraditional - Secure The Family - Top Threats To The Home
- Micro Videos
- -Mod1021-flavorTraditional - Social Engineering - Types of Attacks
- Tradition Animation
- -Mod101-flavorTraditional - You Are the Shield

Change to:

- Mini Game
- -You Are The Shield - On Call
- -Browsing Safely - Secure Shopping
- Gamified
- -Secure The Office - Workstations
- Applied Interactive
- -Applied Interactive Browsing Safely
- Hostled
- -Host Led You Are the Shield
- Illustrative Design
- -Illustrative Design You Are the Shield
- Live Action
- -Live Action You Are the Shield
- Secure The Family
- -Secure The Family - Top Threats To The Home
- Micro Videos
- -Social Engineering - Types of Attacks
- Tradition Animation
- -Tradition Animation You Are the Shield

**Comment by SergioAnderson** [comment]
Fixed
